hackclub/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from django.contrib.auth import views as auth_views
from core import views as core_views

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^post/(?P<pk>\d+)/$',	core_views.post_detail,	name='post_detail'),
    url(r'^submit/', core_views.submit, name='submit_post'),
    url(r'^vote/(?P<pk>\d+)/$', core_views.submit_vote, name='submit_vote'),
    url(r'^send_newsreporter/$', core_views.send_newsreporter, name='send_newsreporter'),
    url(r'^search/$', core_views.search_posts, name='search_post'),
    url(r'^(?P<post_id>\d+)/comments/reply/(?P<parent_id>\d+)$', core_views.comment_reply, name='comment_reply'),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
import operator

from django_markdown.models import MarkdownField
from mptt.models import MPTTModel, TreeForeignKey

from django.db import models
from django.contrib.auth.models import User

class PostManager(models.Manager):
    '''
    sorting news using hackernews sorting algoritm
    https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d
    '''
    def calculate_score(self, votes, item_hour_age, gravity=1.8):
        return (votes - 1) / pow((item_hour_age+2), gravity)

    def get_query_set(self):
        return super(PostManager, self).get_query_set().filter() \
                                       .annotate(vote_score=calculate_score(models.Sum('postvote__vote'), 'published_date__hour')) \
                                       .order_by('vote_score')

class Post(models.Model):
    title = models.CharField(max_length=200)
    user = models.CharField(max_length=150)
    link = models.URLField(max_length=600, blank=True)
    text = models.TextField(blank=True)
    published_date = models.DateTimeField(default=timezone.now)
    score_sorted = PostManager()

    def __unicode__(self):
        return self.title

    def score(self):
        return PostVote.objects.filter(post=self).aggregate(models.Sum('vote'))['vote__sum']

class Comment(MPTTModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=150)
    text = models.TextField(blank=False)
    published_date = models.DateTimeField(default=timezone.now)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by=['published_date']


class PostVote(models.Model):
    VOTE_CHOICES = (
        (1,     'UPVOTE'),
        (0,     'NOVOTE'),
        (-1,    'DOWNVOTE'),
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote = models.IntegerField(choices=VOTE_CHOICES)

core/forms.py
from django import forms
from .models import Post, Comment
from django_markdown.fields import MarkdownFormField
from django_markdown.widgets import MarkdownWidget

class PostForm(forms.ModelForm):
    text = forms.CharField(widget=MarkdownWidget(), required=False)
    class Meta:
        model = Post
        fields = ('title','link', 'text')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('post', 'parent','text')

core/views.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from django.http import HttpResponseRedirect

from django.utils import timezone

from .models import Post, Comment, PostVote
from .forms import PostForm, CommentForm, CommentReplyForm

from .hreporter import Reporter

def home(request):
    post_list = Post.score_sorted.all()
    page = request.GET.get('p', 1)

    paginator = Paginator(post_list, 10)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'post_list.html', {'posts' : posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=pk)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user.username
            comment.post = Post.score_sorted.get(pk=pk)
            comment.published_date = timezone.now()
            comment.save()
    return render(request, 'post_detail.html', {'post'     : post,
                                                'comments' : comments,
                                                'form'     : form })
def comment_reply(request,post_id,parent_id):
    formset = ""
    if request.method == 'POST':
		formset = CommentReplyForm(request.POST)
		if formset.is_valid():
			comment = formset.save(commit=False)
			comment.author = request.user
			comment.save()
			return redirect('/post/' + post_id)
    else:
		comment = Comment()
		comment.post = Post.score_sorted.get(pk=post_id)
		if parent_id != "0":
			comment.parent = Comment.objects.get(pk=parent_id)
		formset = CommentReplyForm(instance=comment)
    formset.fields['post'].widget = forms.HiddenInput()
    formset.fields['parent'].widget = forms.HiddenInput()
    return render(request,"comment_reply.html", {"formset": formset})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

@login_required
def submit(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user.username
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'submit.html', {'form' : form})

@login_required
def submit_vote(request, pk):
    if request.method == 'POST':
        u = User.objects.get(id=request.user.id)
        p = Post.score_sorted.get(id=pk)
        voteargs = request.body.split("&vote=")[1]
        try:
            v, created = PostVote.objects.update_or_create(post=p, user=u)
        except:
            v, created = (PostVote(post=p, user=u, vote=0), True)
        if not created:
            if v.vote != 0:
                v.vote = 0
            else:
                v.vote = get_vote_value(voteargs)
            v.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            v.vote = get_vote_value(voteargs)
            v.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def get_vote_value(voteargs):
    '''
    returns 1 if voteargs is +
    returns -1 if voteargs is -
    '''
    if voteargs == '%2B':
        return 1
    elif voteargs == '-':
        return -1
    else:
        return 0

def send_newsreporter(request):
    r = Reporter()
    r.get_top_thirty_stories()
    return redirect('/')

def search_posts(request):
    searchq = request.GET.get('searchq', '')
    d_posts = []
    posts = Post.score_sorted.annotate(
        search=SearchVector('title', 'text', 'link', 'comment__text')
    ).filter(search=searchq)
    for post in posts:
        if post not in d_posts:
            d_posts.append(post)
    return render(request, 'post_list.html', {'posts' : d_posts, 'searchq' : searchq})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Hackclub{% endblock %}</title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  </head>
  <body>

    {% load poll_extras %}
    <header>
      <h1><a href="/">hackerclub</a></h1>
      {% if user.is_authenticated %}
        Welcome, {{ user.username }}!
        <a href="{% url 'submit_post' %}">Submit</a> |
        <a href="{% url 'logout' %}">logout</a>
      {% else %}
        <a href="{% url 'login' %}">login</a> / <a href="{% url 'signup' %}">signup</a>
      {% endif %}

      <br>
      <br>
      <form method="get" action="/search/" class="navbar-form pull-right">
        <input type="text" id="searchBox" class="input-medium search-query" name="searchq" placeholder="Search" value="{{searchq}}">
        <input type="submit" class="btn" value="Search" >
      </form>
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

templates/comment_reply.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="">
	{% csrf_token %}
    {{ formset }}
    <br/>
    <button type="submit" class="btn">Submit</button>
</form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
  {%	for	post	in	posts	%}
  <div>
          <h1><a	href="{{post.link}}">{{	post.title	}}</a></h1>
          <p>published:	{{	post.published_date	}}</p>
          <p>{{	post.text|linebreaksbr	}}</p>
  </div>
{%	endfor	%}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% load markdown_deux_tags %}
{% load humanize %}

{% load mptt_tags %}
{% load poll_extras %}
{% block content %}
  <div><p>
       {% has_voted post user as voteObj %}
       {% if voteObj.vote == 0  or voteObj == None %}
       <form method="POST" action="{% url 'submit_vote' post.id  %}">
         {% csrf_token %}
         <input type="submit" name="vote" value="+"></input>
         <input type="submit" name="vote" value="-"></input>
       </form>
       {% else %}
       {% if voteObj.vote == 1 %}
       <form method="POST" action="{% url 'submit_vote' post.id  %}">
         {% csrf_token %}
         <input type="submit" name="vote" value="-"></input>
       </form>
       {% else %}
       <form method="POST" action="{% url 'submit_vote' post.id  %}">
         {% csrf_token %}
         <input type="submit" name="vote" value="+"></input>
       </form>
       {% endif %}
       {% endif %}
     </p>
       {% if post.link %}
        <a	href="{{post.link}}">{{	post.title	}}</a>
        {% else %}
        <a	href="/post/{{ post.id}}">{{	post.title	}}</a>
        {% endif %}
       <p>
       {% if post.score %}
       {{post.score}}
       {% else %}
       0
       {% endif %} points submitted by {{post.user}}
     {{ post.published_date | naturaltime }}
        <a href="/post/{{ post.id}}">comments ({{post.comment_set.count}})</a>
      </p>
      <p>
        {% autoescape off %}
        {{post.text | markdown}}
        {% endautoescape %}
      </p>
  </div>
  <hr>

  {% if user.is_authenticated %}
    <form method="POST" class="post-form">{% csrf_token %}
        <textarea name="text" id="id_text" rows="6" cols="60" required=""></textarea><br>
        <button type="submit" class="save btn btn-default">add comment</button>
    </form>

    {% endif %}
{% recursetree comments %}
<div class="comment" style="margin-left: {{ node.get_level }}00px">
</a>{{ node.author }} on {{ node.published_date }}</h5>
        <div>{% autoescape off %}{{ node.text|linebreaks }}{% endautoescape %} </div>
        {% if user.is_authenticated %}<a href="{% url 'comment_reply' post.pk node.pk %}" target="_blank">Reply</a>{% endif %}
</div>
  {% if not node.is_leaf_node %}
      {{ children }}
{% endif %}
{% endrecursetree %}

{% endblock %}

templates/post_list.html
{% extends 'base.html' %}

{% load humanize %}
{% load poll_extras %}
{% block content %}
<div>
  <ol>
  {%	for	post	in	posts	%}
    <li> {% if post.link %}
      <a	href="{{post.link}}">{{	post.title	}}</a>
      {% else %}
      <a	href="/post/{{ post.id}}">{{	post.title	}}</a>
      {% endif %}
      <p>
        {% has_voted post user as voteObj %}
        {% if voteObj.vote == 0  or voteObj == None %}
        <form method="POST" action="{% url 'submit_vote' post.id  %}">
          {% csrf_token %}
          <input type="submit" name="vote" value="+"></input>
          <input type="submit" name="vote" value="-"></input>
        </form>
        {% else %}
        {% if voteObj.vote == 1 %}
        <form method="POST" action="{% url 'submit_vote' post.id  %}">
          {% csrf_token %}
          <input type="submit" name="vote" value="-"></input>
        </form>
        {% else %}
        <form method="POST" action="{% url 'submit_vote' post.id  %}">
          {% csrf_token %}
          <input type="submit" name="vote" value="+"></input>
        </form>
        {% endif %}
        {% endif %}
        {% if post.score %}
        {{post.score}}
        {% else %}
        0
        {% endif %} points submitted by {{post.user}}
      {{ post.published_date | naturaltime }}
         <a href="/post/{{ post.id}}">comments ({{post.comment_set.count}})</a>
       </p>
    </li>
  {%	endfor	%}
</ol>
</div>
{% if posts.has_next %}
<a href="?p={{posts.next_page_number}}">more</a>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/submit.html
{% extends 'base.html' %}

{% load django_markdown %}
{% block content %}
		<h1>Submit</h1>
		<form	method="POST">
			{% csrf_token	%}
			{{	form.as_p	}}
{% markdown_media %}
			<button	type="submit"	class="save	btn	btn-default">Submit</button>
		</form>
{% endblock	%}